import React, { createContext, useContext, useState } from 'react';

const LangContext = createContext();

export const LANG = {
  pt: {
    // General
    appName: 'Pointy Lines',
    subtitle: 'Cria infinitas combinações de tricot',
    save: 'Guardar',
    load: 'Carregar',
    cancel: 'Cancelar',
    apply: 'Aplicar',
    close: 'Fechar',
    delete: 'Remover',

    // Home
    stitchEditor: 'Editor de Pontos',
    colorworkEditor: 'Editor Jacquard',
    stitchBlanket: 'Manta de Pontos',
    toyPattern: 'Brinquedos',
    imageToChart: 'Imagem para Gráfico',
    stitchEditorDesc: 'Cria padrões de pontos para camisolas, calças, meias, bonecos',
    colorworkEditorDesc: 'Desenha padrões coloridos com cores específicas',
    stitchBlanketDesc: 'Combina padrões de meia e liga como as mantas Purl Soho',
    toyPatternDesc: 'Transforme uma imagem num brinquedo de tricô',
    imageToChartDesc: 'Converte uma imagem em gráfico de tricô com tamanho e padrão',
    yarnColors: 'Cores do Fio',
    yarnColorsHint: 'Toca numa cor para alterar',
    patternGallery: 'Galeria de Padrões',

    // Stitch Editor
    editTitle: 'Editor de Pontos',
    editSubtitle: 'Desenha cada secção e gera o PDF com guia de montagem',
    garmentType: 'Tipo de Peça',
    sections: 'Secções',
    section: 'Secção',
    width: 'Larg (pts)',
    height: 'Alt (carr)',
    gauge: 'Amostra (10 cm)',
    stitchesLabel: 'Pontos',
    rowsLabel: 'Carreiras',
    measurements: 'Medidas da Peça (cm)',
    chest: 'Larg.',
    length: 'Comp.',
    sleeve: 'Manga',
    calculate: 'Calcular',
    assistant: 'Assistente Interativo',
    projectName: 'Nome do Projeto (opcional)',
    imagePdf: 'Imagem para o PDF (opcional)',
    chooseImage: '📁 Escolher Imagem',
    notes: 'Notas / Descrição (opcional)',
    pdfIncludes: 'O PDF vai incluir:',
    pdfChart: 'Gráfico de cada secção (frente, costas, etc.)',
    pdfGuide: 'Guia de montagem',
    pdfInstructions: 'Instruções carreira-a-carreira',
    pdfTable: 'Tabela de medidas',
    generatePdf: '📄 Gerar PDF Completo',
    generateRecipe: '📖 Gerar Receita',
    savePattern: 'Guardar Padrão',
    patternLibrary: '📚 Biblioteca',
    preview: '🔍 Ver preview dos pontos',
    previewTitle: 'Pré-visualização',
    editSweater: 'Editar Sweater',
    exportPng: '⬇ PNG',
    exportSvg: '⬇ SVG',
    knitFlat: 'Plano',
    knitRound: 'Redondo',
    paint: '🎨 Pintar',
    select: '🔲 Selecionar',
    aumDim: '📐 Aum/Dim',
    copy: 'Copiar',
    paste: 'Colar',
    resize: 'Redimensionar',
    clear: 'Limpar',
    fillAll: 'Preencher tudo com',
    undo: '↶',
    redo: '↷',
    zoom: 'Zoom',
    recipe: 'Receita de Tricô',
    needle: 'Agulha',
    yarnEstimate: 'Lã',

    // Assistant
    assistTitle: 'Assistente',
    assistSections: 'Secções:',
    assistAction: 'Ação:',
    assistFillRows: 'Preencher Carreiras',
    assistFillCols: 'Preencher Malhas',
    assistRowPattern: 'Padrão na Carreira',
    assistClear: 'Limpar',
    assistAlternate: 'Alternar',
    assistIncrease: 'Aumentos',
    assistDecrease: 'Diminuições',
    assistNeckline: 'Gola/Decote',
    assistMirrorH: 'Espelhar ↔',
    assistStitch: 'Ponto:',
    assistRange: 'Carreiras (ex: 1-10):',
    assistColRange: 'Malhas (ex: 1-10):',
    assistPattern: 'Padrão (ex: 3m 2l 5m 2l 3m):',
    assistEvery: 'A cada N carreiras:',
    assistNeckStart: 'Início do decote (a quantas carreiras do topo):',
    assistNeckWidth: 'Largura do decote (malhas ao centro):',
    assistNeckHint: 'Marca ombros com m e decote com ✕',
    assistPatternHint: 'Número seguido de ponto: m, l, t, b, bo, 2pm, 3pm',
    all: 'Todas',
    front: 'Frente',
    back: 'Costas',
    sleeve: 'Manga',
    front_left: 'Frente Esq.',
    front_right: 'Frente Dir.',
    leg: 'Perna',
    foot: 'Pé',
    body: 'Corpo',
    size: 'Tamanho',
    saveLoad: 'Guardar / Carregar',
    instructions: 'Instruções:',
    remove: 'Remover',
    knitType: 'Tricotar',
    sweater: 'Camisola',
    jacket: 'Casaco',
    pants: 'Calças',
    socks: 'Meias',
    toy: 'Boneco',
    camera: '📷 Câmara',
    projectNamePlaceholder: 'Ex: Camisola Azul',
    notesPlaceholder: 'Ex: Usar lã merino, agulha 4mm, costurar com ponto invisível...',
    savePatternTitle: 'Guardar como Padrão',
    patternNamePlaceholder: 'Nome do padrão',
    previewLabel: 'Preview —',
    pdfChartDetail: 'Gráfico de cada secção (frente, costas, etc.)',
    pdfGuideDetail: 'Guia de montagem',
    pdfInstructionsDetail: 'Instruções carreira-a-carreira',
    pdfTableDetail: 'Tabela de medidas',
    stitchToolbar: 'Ponto',
    stitchMeia: 'Meia',
    stitchLiga: 'Liga',
    stitchTorcido: 'Torcido',
    stitchBuraco: 'Buraco',
    stitchBola: 'Bola',
    stitch2pm: '2pM',
    stitch3pm: '3pM',
    stitchFora: 'Fora',
    altRows: 'Carreiras (ex: 1-10 ou 1,3,5):',
    altCols: 'Malhas (ex: 1-10):',
    altPattern: 'Padrão (ex: 3m 2l 5m 2l 3m):',
    altStitchSep: 'Pontos (separados por espaço, ex: m l):',
    altEvery: 'A cada N carreiras:',
    altNeckStart: 'Início do decote (a quantas carreiras do topo):',
    altNeckWidth: 'Largura do decote (malhas ao centro):',
    altNeckHintDetail: "Marca ombros com 'm' e decote com '✕' (fora). Aplica na secção ativa.",
    altRowPattern: 'Carreiras (ex: 1-10 ou 1,3,5):',
    noCommand: 'Comando não reconhecido. Ex: "frente carreira 1-10 com t", "costas toda com m", "manga malha 5 com l", "todas alternar m l a cada 2"',
    copyAlert: 'Seleciona uma área primeiro',
    pasteAlert: 'Nada para colar',
    copied: 'Copiado',
    enterMeasurement: 'Insere pelo menos uma medida em cm',
    previewError: 'Erro ao gerar preview',
    recipeError: 'Erro ao gerar receita',
    savePatternError: 'Erro ao guardar padrão',
    savePatternSuccess: 'Padrão adicionado à biblioteca',
    permissionNeeded: 'Permissão necessária',
    permissionDesc: 'Precisamos de acesso à galeria.',
    generatedSuccess: 'Aplicado com sucesso!',
    needName: 'Dá um nome ao padrão',
    nameSaved: 'Guardado!',
    namePattern: 'Padrão criado no editor',
    errorGeneric: 'Erro',
    errorPdf: 'Erro ao gerar PDF',
    garmentInfo: 'para',
    // Image to Chart
    imageToChartTitle: 'Imagem para Gráfico',
    imageToChartSize: 'Tamanho da Peça',
    imageToChartPattern: 'Padrão de Pontos',
    imageToChartImage: 'Imagem',
    imageToChartAutoFill: '🔮 Converter',
    imageToChartPdf: '📄 Gerar PDF',
    imageToChartNoPattern: 'Nenhum',
    imageToChartLoading: 'A converter...',
    imageToChartSuccess: 'Gráfico gerado — {w}×{h} pontos',
    imageToChartError: 'Erro ao converter imagem',
    imageToChartPickImage: '📁 Escolher Imagem',
    imageToChartImageSelected: '✅ Imagem selecionada',
    imageToChartPreview: 'Pré-visualização do gráfico',
    imageToChartNoImage: 'Seleciona uma imagem primeiro',
    imageToChartSelectPattern: 'Tocar para escolher',
  },
  en: {
    appName: 'Pointy Lines',
    subtitle: 'Create endless knitting combinations',
    save: 'Save',
    load: 'Load',
    cancel: 'Cancel',
    apply: 'Apply',
    close: 'Close',
    delete: 'Delete',

    stitchEditor: 'Stitch Editor',
    colorworkEditor: 'Colorwork Editor',
    stitchBlanket: 'Stitch Blanket',
    toyPattern: 'Toys',
    imageToChart: 'Image to Chart',
    stitchEditorDesc: 'Create stitch patterns for sweaters, pants, socks, toys',
    colorworkEditorDesc: 'Draw colorwork patterns with specific colors',
    stitchBlanketDesc: 'Combine knit and purl patterns like Purl Soho blankets',
    toyPatternDesc: 'Turn an image into a knitted toy',
    imageToChartDesc: 'Convert an image to a knitting chart with size and pattern',
    yarnColors: 'Yarn Colors',
    yarnColorsHint: 'Tap a color to change it',
    patternGallery: 'Pattern Gallery',

    editTitle: 'Stitch Editor',
    editSubtitle: 'Draw each section and generate PDF with assembly guide',
    garmentType: 'Garment Type',
    sections: 'Sections',
    section: 'Section',
    width: 'Width (sts)',
    height: 'Height (rows)',
    gauge: 'Gauge (10 cm)',
    stitchesLabel: 'Stitches',
    rowsLabel: 'Rows',
    measurements: 'Garment Measurements (cm)',
    chest: 'Width',
    length: 'Length',
    sleeve: 'Sleeve',
    calculate: 'Calculate',
    assistant: 'Interactive Assistant',
    projectName: 'Project Name (optional)',
    imagePdf: 'Image for PDF (optional)',
    chooseImage: '📁 Choose Image',
    notes: 'Notes / Description (optional)',
    pdfIncludes: 'PDF will include:',
    pdfChart: 'Chart for each section (front, back, etc.)',
    pdfGuide: 'Assembly guide',
    pdfInstructions: 'Row-by-row instructions',
    pdfTable: 'Measurement table',
    generatePdf: '📄 Generate Full PDF',
    generateRecipe: '📖 Generate Recipe',
    savePattern: 'Save Pattern',
    patternLibrary: '📚 Library',
    preview: '🔍 Preview stitches',
    previewTitle: 'Preview',
    editSweater: 'Edit Sweater',
    exportPng: '⬇ PNG',
    exportSvg: '⬇ SVG',
    knitFlat: 'Flat',
    knitRound: 'Round',
    paint: '🎨 Paint',
    select: '🔲 Select',
    aumDim: '📐 Inc/Dec',
    copy: 'Copy',
    paste: 'Paste',
    resize: 'Resize',
    clear: 'Clear',
    fillAll: 'Fill all with',
    undo: '↶',
    redo: '↷',
    zoom: 'Zoom',
    recipe: 'Knitting Recipe',
    needle: 'Needle',
    yarnEstimate: 'Yarn',

    assistTitle: 'Assistant',
    assistSections: 'Sections:',
    assistAction: 'Action:',
    assistFillRows: 'Fill Rows',
    assistFillCols: 'Fill Columns',
    assistRowPattern: 'Row Pattern',
    assistClear: 'Clear',
    assistAlternate: 'Alternate',
    assistIncrease: 'Increases',
    assistDecrease: 'Decreases',
    assistNeckline: 'Neckline',
    assistMirrorH: 'Mirror ↔',
    assistStitch: 'Stitch:',
    assistRange: 'Rows (e.g. 1-10):',
    assistColRange: 'Columns (e.g. 1-10):',
    assistPattern: 'Pattern (e.g. 3RS 2WS 5RS 2WS 3RS):',
    assistEvery: 'Every N rows:',
    assistNeckStart: 'Neck start (rows from top):',
    assistNeckWidth: 'Neck width (center stitches):',
    assistNeckHint: 'Marks shoulders with m and neckline with ✕',
    assistPatternHint: 'Number followed by stitch: m, l, t, b, bo, 2pm, 3pm',
    all: 'All',
    front: 'Front',
    back: 'Back',
    sleeve: 'Sleeve',
    front_left: 'Front Left',
    front_right: 'Front Right',
    leg: 'Leg',
    foot: 'Foot',
    body: 'Body',
    size: 'Size',
    saveLoad: 'Save / Load',
    instructions: 'Instructions:',
    remove: 'Remove',
    knitType: 'Knit',
    sweater: 'Sweater',
    jacket: 'Jacket',
    pants: 'Pants',
    socks: 'Socks',
    toy: 'Toy',
    camera: '📷 Camera',
    projectNamePlaceholder: 'Ex: Blue Sweater',
    notesPlaceholder: 'Ex: Merino wool, 4mm needle, invisible seam...',
    savePatternTitle: 'Save as Pattern',
    patternNamePlaceholder: 'Pattern name',
    previewLabel: 'Preview —',
    pdfChartDetail: 'Chart for each section (front, back, etc.)',
    pdfGuideDetail: 'Assembly guide',
    pdfInstructionsDetail: 'Row-by-row instructions',
    pdfTableDetail: 'Measurement table',
    stitchToolbar: 'Stitch',
    stitchMeia: 'Stockinette',
    stitchLiga: 'Garter',
    stitchTorcido: 'Cable Stitch',
    stitchBuraco: 'Hole',
    stitchBola: 'Bobble',
    stitch2pm: 'K2tog',
    stitch3pm: 'K3tog',
    stitchFora: 'Out',
    altRows: 'Rows (e.g. 1-10 or 1,3,5):',
    altCols: 'Columns (e.g. 1-10):',
    altPattern: 'Pattern (e.g. 3m 2l 5m 2l 3m):',
    altStitchSep: 'Stitches (space separated, e.g. m l):',
    altEvery: 'Every N rows:',
    altNeckStart: 'Neck start (rows from top):',
    altNeckWidth: 'Neck width (center stitches):',
    altNeckHintDetail: "Marks shoulders with 'm' and neckline with '✕' (out). Applies to active section.",
    altRowPattern: 'Rows (e.g. 1-10 or 1,3,5):',
    noCommand: 'Unknown command. Ex: "front rows 1-10 with t", "back all with m", "sleeve col 5 with l", "all alternate m l every 2"',
    copyAlert: 'Select an area first',
    pasteAlert: 'Nothing to paste',
    copied: 'Copied',
    enterMeasurement: 'Enter at least one measurement in cm',
    previewError: 'Error generating preview',
    recipeError: 'Error generating recipe',
    savePatternError: 'Error saving pattern',
    savePatternSuccess: 'Pattern added to library',
    permissionNeeded: 'Permission needed',
    permissionDesc: 'We need access to your gallery.',
    generatedSuccess: 'Applied successfully!',
    needName: 'Give the pattern a name',
    nameSaved: 'Saved!',
    namePattern: 'Pattern created in editor',
    errorGeneric: 'Error',
    errorPdf: 'Error generating PDF',
    garmentInfo: 'for',
    // Image to Chart
    imageToChartTitle: 'Image to Chart',
    imageToChartSize: 'Garment Size',
    imageToChartPattern: 'Stitch Pattern',
    imageToChartImage: 'Image',
    imageToChartAutoFill: '🔮 Convert',
    imageToChartPdf: '📄 Generate PDF',
    imageToChartNoPattern: 'None',
    imageToChartLoading: 'Converting...',
    imageToChartSuccess: 'Chart generated — {w}×{h} stitches',
    imageToChartError: 'Error converting image',
    imageToChartPickImage: '📁 Choose Image',
    imageToChartImageSelected: '✅ Image selected',
    imageToChartPreview: 'Chart preview',
    imageToChartNoImage: 'Select an image first',
    imageToChartSelectPattern: 'Tap to choose',
  },
};

export function LangProvider({ children }) {
  const [lang, setLang] = useState('pt');
  return (
    <LangContext.Provider value={{ lang, setLang, t: LANG[lang] }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) return { lang: 'pt', setLang: () => {}, t: LANG.pt };
  return ctx;
}
