STITCH_LIBRARY = {
    "stockinette": {
        "name": "Ponto Meia",
        "category": "basicos",
        "difficulty": 1,
        "description": "Clássico ponto meia — liso e versátil",
        "chart": [[0]],
        "repeat_w": 1,
        "repeat_h": 1,
        "tags": ["liso", "direito"],
    },
    "garter": {
        "name": "Ponto Jarreteira",
        "category": "basicos",
        "difficulty": 1,
        "description": "Tricotar todas as carreiras — textura ondulada",
        "chart": [[0]],
        "repeat_w": 1,
        "repeat_h": 1,
        "tags": ["ondulado", "reversivel"],
        "note": "Tricotar todos os pontos em todas as carreiras",
    },
    "seed": {
        "name": "Ponto Arroz",
        "category": "basicos",
        "difficulty": 1,
        "description": "Alterna 1 meia, 1 liga — textura granulada",
        "chart": [[0, 1], [1, 0]],
        "repeat_w": 2,
        "repeat_h": 2,
        "tags": ["textura", "reversivel"],
    },
    "double_moss": {
        "name": "Ponto Musgo Duplo",
        "category": "basicos",
        "difficulty": 1,
        "description": "4 carreiras de arroz alternadas — textura rica",
        "chart": [
            [0, 1, 0, 1],
            [0, 1, 0, 1],
            [1, 0, 1, 0],
            [1, 0, 1, 0],
        ],
        "repeat_w": 4,
        "repeat_h": 4,
        "tags": ["textura", "reversivel"],
    },
    "irish_moss": {
        "name": "Ponto Musgo Irlandês",
        "category": "basicos",
        "difficulty": 1,
        "description": "Versão do musgo com mais relevo",
        "chart": [
            [0, 1, 1, 0],
            [0, 1, 1, 0],
            [1, 0, 0, 1],
            [1, 0, 0, 1],
        ],
        "repeat_w": 4,
        "repeat_h": 4,
        "tags": ["textura", "relevo"],
    },
    "moss": {
        "name": "Ponto Musgo",
        "category": "basicos",
        "difficulty": 1,
        "description": "Variação do arroz com padrão de 4 carreiras",
        "chart": [[0, 1, 1, 0], [0, 1, 1, 0], [1, 0, 0, 1], [1, 0, 0, 1]],
        "repeat_w": 4,
        "repeat_h": 4,
        "tags": ["textura"],
    },
    "sand_stitch": {
        "name": "Ponto Areia",
        "category": "basicos",
        "difficulty": 1,
        "description": "Textura fina que lembra areia",
        "chart": [
            [0, 1],
            [1, 0],
        ],
        "repeat_w": 2,
        "repeat_h": 2,
        "tags": ["textura", "fino"],
    },
    "seersucker": {
        "name": "Ponto Seersucker",
        "category": "basicos",
        "difficulty": 1,
        "description": "Ondulado suave tipo sarja",
        "chart": [
            [0, 0, 1, 1],
            [0, 0, 1, 1],
            [1, 1, 0, 0],
            [1, 1, 0, 0],
        ],
        "repeat_w": 4,
        "repeat_h": 4,
        "tags": ["ondulado", "sarja"],
    },
    "parallelogram": {
        "name": "Ponto Paralelogramo",
        "category": "basicos",
        "difficulty": 1,
        "description": "Blocos inclinados de meia e liga",
        "chart": [
            [1, 1, 0, 0],
            [1, 0, 0, 1],
            [0, 0, 1, 1],
            [0, 1, 1, 0],
        ],
        "repeat_w": 4,
        "repeat_h": 4,
        "tags": ["geometrico", "inclinado"],
    },
    "hurdle": {
        "name": "Ponto Barreira",
        "category": "basicos",
        "difficulty": 1,
        "description": "Faixas horizontais de meia e liga",
        "chart": [
            [0, 0, 0, 0],
            [1, 1, 1, 1],
        ],
        "repeat_w": 4,
        "repeat_h": 2,
        "tags": ["listras", "horizontal"],
    },
    "welt": {
        "name": "Ponto Dobra",
        "category": "basicos",
        "difficulty": 2,
        "description": "Dobras horizontais com carreiras de liga",
        "chart": [
            [0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0],
            [1, 1, 1, 1, 1, 1],
        ],
        "repeat_w": 6,
        "repeat_h": 4,
        "tags": ["dobra", "relevo"],
    },
    "rib_1x1": {
        "name": "Canelado 1x1",
        "category": "canelados",
        "difficulty": 1,
        "description": "1 meia, 1 liga — elástico e clássico",
        "chart": [[0, 1]],
        "repeat_w": 2,
        "repeat_h": 1,
        "tags": ["elastico", "classico"],
    },
    "rib_2x2": {
        "name": "Canelado 2x2",
        "category": "canelados",
        "difficulty": 1,
        "description": "2 meias, 2 ligas — mais largo que o 1x1",
        "chart": [[0, 0, 1, 1]],
        "repeat_w": 4,
        "repeat_h": 1,
        "tags": ["elastico", "largo"],
    },
    "rib_3x1": {
        "name": "Canelado 3x1",
        "category": "canelados",
        "difficulty": 1,
        "description": "3 meias, 1 liga — canelado assimétrico",
        "chart": [[0, 0, 0, 1]],
        "repeat_w": 4,
        "repeat_h": 1,
        "tags": ["elastico", "assimetrico"],
    },
    "rib_3x2": {
        "name": "Canelado 3x2",
        "category": "canelados",
        "difficulty": 1,
        "description": "3 meias, 2 ligas",
        "chart": [[0, 0, 0, 1, 1]],
        "repeat_w": 5,
        "repeat_h": 1,
        "tags": ["elastico"],
    },
    "seeded_rib": {
        "name": "Canelado com Arroz",
        "category": "canelados",
        "difficulty": 1,
        "description": "Canelado com textura de arroz nas vales",
        "chart": [
            [0, 1, 0, 1],
            [0, 1, 0, 1],
            [0, 0, 1, 1],
            [0, 0, 1, 1],
        ],
        "repeat_w": 4,
        "repeat_h": 4,
        "tags": ["canelado", "textura"],
    },
    "beaded_rib": {
        "name": "Canelado com Contas",
        "category": "canelados",
        "difficulty": 2,
        "description": "Canelado com pontos tipo conta",
        "chart": [
            [0, 1, 0, 1],
            [0, 1, 0, 1],
            [1, 0, 1, 0],
            [1, 0, 1, 0],
        ],
        "repeat_w": 4,
        "repeat_h": 4,
        "tags": ["canelado", "contas"],
    },
    "garter_rib": {
        "name": "Canelado Jarreteira",
        "category": "canelados",
        "difficulty": 1,
        "description": "Canelado com fundo em jarreteira",
        "chart": [
            [0, 1],
            [1, 0],
        ],
        "repeat_w": 2,
        "repeat_h": 2,
        "tags": ["canelado", "jarreteira"],
    },
    "chevron_rib": {
        "name": "Canelado Chevron",
        "category": "canelados",
        "difficulty": 2,
        "description": "Canelado em V — textura diagonal",
        "chart": [
            [0, 0, 1, 1, 1, 1],
            [0, 0, 1, 1, 1, 1],
            [1, 1, 0, 0, 1, 1],
            [1, 1, 0, 0, 1, 1],
        ],
        "repeat_w": 6,
        "repeat_h": 4,
        "tags": ["chevron", "diagonal"],
    },
    "spiral_rib": {
        "name": "Canelado Espiral",
        "category": "canelados",
        "difficulty": 2,
        "description": "Canelado torcido em espiral",
        "chart": [
            [1, 1, 1, 0],
            [1, 1, 0, 1],
            [1, 0, 1, 1],
            [0, 1, 1, 1],
        ],
        "repeat_w": 4,
        "repeat_h": 4,
        "tags": ["espiral", "torcido"],
    },
    "check_2x2": {
        "name": "Quadrados 2x2",
        "category": "basket_weave",
        "difficulty": 1,
        "description": "Blocos de 2 meias, 2 ligas em xadrez",
        "chart": [[0, 0, 1, 1], [0, 0, 1, 1], [1, 1, 0, 0], [1, 1, 0, 0]],
        "repeat_w": 4,
        "repeat_h": 4,
        "tags": ["xadrez", "blocos"],
    },
    "check_4x4": {
        "name": "Quadrados 4x4",
        "category": "basket_weave",
        "difficulty": 1,
        "description": "Blocos grandes de meia e liga",
        "chart": [
            [0, 0, 0, 0, 1, 1, 1, 1],
            [0, 0, 0, 0, 1, 1, 1, 1],
            [0, 0, 0, 0, 1, 1, 1, 1],
            [0, 0, 0, 0, 1, 1, 1, 1],
            [1, 1, 1, 1, 0, 0, 0, 0],
            [1, 1, 1, 1, 0, 0, 0, 0],
            [1, 1, 1, 1, 0, 0, 0, 0],
            [1, 1, 1, 1, 0, 0, 0, 0],
        ],
        "repeat_w": 8,
        "repeat_h": 8,
        "tags": ["xadrez", "blocos grandes"],
    },
    "basketweave": {
        "name": "Entrançado",
        "category": "basket_weave",
        "difficulty": 1,
        "description": "Trama de cestaria com meia e liga",
        "chart": [
            [0, 0, 0, 1, 1, 1],
            [0, 0, 0, 1, 1, 1],
            [0, 0, 0, 1, 1, 1],
            [1, 1, 1, 0, 0, 0],
            [1, 1, 1, 0, 0, 0],
            [1, 1, 1, 0, 0, 0],
        ],
        "repeat_w": 6,
        "repeat_h": 6,
        "tags": ["cestaria", "trama"],
    },
    "garter_checkerboard": {
        "name": "Xadrez Jarreteira",
        "category": "basket_weave",
        "difficulty": 2,
        "description": "Xadrez com textura de jarreteira intercalada",
        "chart": [
            [0, 0, 0, 0, 1, 1, 1, 1],
            [0, 0, 0, 0, 1, 1, 1, 1],
            [0, 0, 0, 0, 1, 1, 1, 1],
            [0, 0, 0, 0, 1, 1, 1, 1],
            [1, 1, 1, 1, 0, 0, 0, 0],
            [1, 1, 1, 1, 0, 0, 0, 0],
            [1, 1, 1, 1, 0, 0, 0, 0],
            [1, 1, 1, 1, 0, 0, 0, 0],
        ],
        "repeat_w": 8,
        "repeat_h": 8,
        "tags": ["xadrez", "jarreteira"],
    },
    "basket_loop": {
        "name": "Laço de Cesto",
        "category": "basket_weave",
        "difficulty": 2,
        "description": "Trama entrançada com laços",
        "chart": [
            [1, 1, 0, 0, 0, 0],
            [1, 1, 0, 0, 0, 0],
            [1, 1, 0, 0, 0, 0],
            [0, 0, 0, 1, 1, 0],
            [0, 0, 0, 1, 1, 0],
            [0, 0, 0, 1, 1, 0],
        ],
        "repeat_w": 6,
        "repeat_h": 6,
        "tags": ["cestaria", "lacos"],
    },
    "lattice_seed": {
        "name": "Treliça Arroz",
        "category": "basket_weave",
        "difficulty": 2,
        "description": "Treliça com pontos de arroz",
        "chart": [
            [0, 0, 1, 1, 0, 0, 1, 1, 0, 0],
            [0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
            [1, 0, 0, 0, 1, 1, 0, 0, 0, 1],
            [1, 1, 0, 0, 1, 1, 0, 0, 1, 1],
            [0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
            [0, 0, 1, 1, 0, 0, 1, 1, 0, 0],
            [0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
            [1, 0, 0, 0, 1, 1, 0, 0, 0, 1],
        ],
        "repeat_w": 10,
        "repeat_h": 8,
        "tags": ["trelica", "arroz"],
    },
    "diagonal": {
        "name": "Diagonal",
        "category": "diagonais",
        "difficulty": 1,
        "description": "Linhas diagonais de meia em fundo liga",
        "chart": [
            [1, 1, 1, 0],
            [1, 1, 0, 1],
            [1, 0, 1, 1],
            [0, 1, 1, 1],
        ],
        "repeat_w": 4,
        "repeat_h": 4,
        "tags": ["diagonal", "riscas"],
    },
    "diagonal_reverse": {
        "name": "Diagonal Reversa",
        "category": "diagonais",
        "difficulty": 1,
        "description": "Diagonal no sentido oposto",
        "chart": [
            [0, 1, 1, 1],
            [1, 0, 1, 1],
            [1, 1, 0, 1],
            [1, 1, 1, 0],
        ],
        "repeat_w": 4,
        "repeat_h": 4,
        "tags": ["diagonal", "reverso"],
    },
    "diagonal_spiral_rib": {
        "name": "Espiral Diagonal",
        "category": "diagonais",
        "difficulty": 2,
        "description": "Diagonal com textura de canelado",
        "chart": [
            [1, 0, 0, 1],
            [0, 1, 0, 1],
            [0, 0, 1, 1],
            [0, 0, 1, 1],
        ],
        "repeat_w": 4,
        "repeat_h": 4,
        "tags": ["espiral", "canelado"],
    },
    "chevron_zigzag": {
        "name": "Ziguezague Chevron",
        "category": "diagonais",
        "difficulty": 2,
        "description": "Ziguezague de meia em fundo liga",
        "chart": [
            [1, 1, 1, 0, 1, 1],
            [1, 1, 0, 0, 0, 1],
            [1, 0, 0, 1, 0, 0],
            [0, 0, 1, 1, 1, 0],
            [0, 0, 0, 1, 0, 0],
            [0, 1, 1, 1, 0, 0],
        ],
        "repeat_w": 6,
        "repeat_h": 6,
        "tags": ["ziguezague", "chevron"],
    },
    "cut_diagonals": {
        "name": "Diagonais Cortadas",
        "category": "diagonais",
        "difficulty": 2,
        "description": "Diagonais com cortes intercalados",
        "chart": [
            [1, 1, 1, 0, 0, 1, 1, 1],
            [1, 1, 0, 0, 0, 0, 1, 1],
            [1, 0, 0, 0, 0, 0, 0, 1],
            [0, 0, 0, 0, 1, 0, 0, 0],
            [0, 0, 0, 1, 0, 0, 0, 0],
            [1, 0, 0, 0, 0, 0, 0, 1],
            [1, 1, 0, 0, 0, 0, 1, 1],
            [1, 1, 1, 0, 0, 1, 1, 1],
        ],
        "repeat_w": 8,
        "repeat_h": 8,
        "tags": ["diagonal", "cortado"],
    },
    "diagonal_seed": {
        "name": "Arroz Diagonal",
        "category": "diagonais",
        "difficulty": 2,
        "description": "Diagonal com textura de ponto arroz",
        "chart": [
            [1, 0, 0, 1, 0, 0],
            [1, 1, 0, 1, 0, 0],
            [0, 1, 0, 0, 1, 0],
            [0, 0, 1, 0, 1, 1],
            [0, 0, 1, 0, 0, 1],
            [0, 0, 0, 1, 0, 0],
        ],
        "repeat_w": 6,
        "repeat_h": 6,
        "tags": ["diagonal", "arroz"],
    },
    "diamond_brocade": {
        "name": "Brocado Diamante",
        "category": "diamantes",
        "difficulty": 2,
        "description": "Losangos de meia em fundo liga",
        "chart": [
            [1, 1, 1, 0, 1, 1, 1, 1],
            [1, 1, 0, 0, 0, 1, 1, 1],
            [1, 0, 0, 0, 0, 0, 1, 1],
            [0, 0, 0, 1, 0, 0, 0, 1],
            [0, 0, 0, 0, 0, 0, 0, 0],
            [1, 0, 0, 0, 0, 0, 1, 0],
            [1, 1, 0, 0, 0, 1, 1, 0],
            [1, 1, 1, 0, 1, 1, 1, 0],
        ],
        "repeat_w": 8,
        "repeat_h": 8,
        "tags": ["losango", "brocado"],
    },
    "fancy_diamond": {
        "name": "Diamante Fantasia",
        "category": "diamantes",
        "difficulty": 3,
        "description": "Diamantes elaborados com pontos liga",
        "chart": [
            [1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1],
            [1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1],
            [1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1],
            [0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0],
            [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
            [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
            [1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1],
            [1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
            [1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1],
        ],
        "repeat_w": 12,
        "repeat_h": 12,
        "tags": ["diamante", "elaborado"],
    },
    "broken_rib": {
        "name": "Canelado Quebrado",
        "category": "diamantes",
        "difficulty": 2,
        "description": "Interrupções no canelado criam textura de diamante",
        "chart": [
            [0, 1, 0, 1, 1, 0, 1, 0],
            [0, 1, 0, 1, 1, 0, 1, 0],
        ],
        "repeat_w": 8,
        "repeat_h": 2,
        "tags": ["canelado", "quebrado"],
    },
    "granite": {
        "name": "Granito",
        "category": "rendas",
        "difficulty": 2,
        "description": "Textura granítica com meia e liga",
        "chart": [
            [0, 1, 0, 1],
            [1, 0, 1, 0],
            [0, 1, 0, 1],
            [1, 0, 1, 0],
        ],
        "repeat_w": 4,
        "repeat_h": 4,
        "tags": ["granito", "textura"],
    },
    "mesh_lace": {
        "name": "Renda Malha",
        "category": "rendas",
        "difficulty": 3,
        "description": "Padrão rendado aberto tipo malha",
        "chart": [
            [0, 1, 0, 1],
            [1, 0, 1, 0],
        ],
        "repeat_w": 4,
        "repeat_h": 2,
        "tags": ["renda", "malha", "aberto"],
    },
    "linen": {
        "name": "Ponto Linho",
        "category": "deslizados",
        "difficulty": 2,
        "description": "Ponto deslizado que imita tecido de linho",
        "chart": [
            [0, 1, 0, 1],
            [1, 0, 1, 0],
        ],
        "repeat_w": 4,
        "repeat_h": 2,
        "tags": ["linho", "deslizado"],
    },
    "butterfly": {
        "name": "Ponto Borboleta",
        "category": "deslizados",
        "difficulty": 3,
        "description": "Pontos deslizados formam borboletas",
        "chart": [
            [1, 1, 0, 1, 1, 1, 1, 1],
            [1, 1, 0, 1, 1, 1, 1, 1],
            [1, 1, 0, 1, 1, 1, 1, 1],
            [0, 0, 0, 0, 0, 0, 0, 0],
            [1, 1, 1, 1, 1, 0, 1, 1],
            [1, 1, 1, 1, 1, 0, 1, 1],
            [1, 1, 1, 1, 1, 0, 1, 1],
            [0, 0, 0, 0, 0, 0, 0, 0],
        ],
        "repeat_w": 8,
        "repeat_h": 8,
        "tags": ["borboleta", "deslizado"],
    },
    "tiles": {
        "name": "Azulejo",
        "category": "outros",
        "difficulty": 2,
        "description": "Padrão de azulejos em meia e liga",
        "chart": [
            [1, 1, 0, 1, 1, 1],
            [1, 0, 0, 0, 1, 1],
            [0, 0, 0, 0, 0, 1],
            [1, 0, 0, 0, 0, 0],
            [1, 1, 0, 0, 0, 1],
            [1, 1, 1, 0, 1, 1],
        ],
        "repeat_w": 6,
        "repeat_h": 6,
        "tags": ["azulejo", "geometrico"],
    },
    "heart_square": {
        "name": "Quadrado Coração",
        "category": "coracoes",
        "difficulty": 2,
        "description": "Coração em ponto liga sobre fundo meia",
        "chart": [
            [1, 1, 0, 1, 1, 1, 0, 1, 1, 1],
            [1, 0, 0, 0, 1, 0, 0, 0, 1, 1],
            [0, 0, 1, 0, 0, 0, 1, 0, 0, 1],
            [0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
            [1, 0, 0, 0, 0, 0, 0, 0, 1, 1],
            [1, 1, 0, 0, 0, 0, 0, 1, 1, 1],
            [1, 1, 1, 0, 0, 0, 1, 1, 1, 1],
            [1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        ],
        "repeat_w": 10,
        "repeat_h": 10,
        "tags": ["coracao", "decorativo"],
    },
    "heel_stitch": {
        "name": "Ponto Calcanhar",
        "category": "meias",
        "difficulty": 2,
        "description": "Clássico ponto deslizado para reforço do calcanhar de meias",
        "chart": [
            [0, 1, 0, 1],
            [1, 0, 1, 0],
            [0, 1, 0, 1],
            [1, 0, 1, 0],
        ],
        "repeat_w": 4,
        "repeat_h": 4,
        "tags": ["calcanhar", "meia", "reforco"],
    },
    "sock_cuff_rib": {
        "name": "Canelado Punho Meia",
        "category": "meias",
        "difficulty": 1,
        "description": "Canelado 3x2 tradicional para punhos de meia",
        "chart": [
            [1, 1, 1, 0, 0],
        ],
        "repeat_w": 5,
        "repeat_h": 1,
        "tags": ["canelado", "meia", "punho"],
    },
    "toe_shaping": {
        "name": "Formato Ponta do Pé",
        "category": "meias",
        "difficulty": 3,
        "description": "Indicação visual de diminuições para bico da meia",
        "chart": [
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
            [1, 1, 0, 0, 0, 0, 0, 0, 1, 1],
            [1, 1, 1, 0, 0, 0, 0, 1, 1, 1],
            [1, 1, 1, 1, 0, 0, 1, 1, 1, 1],
            [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        ],
        "repeat_w": 10,
        "repeat_h": 10,
        "tags": ["meia", "bico", "diminuicao"],
    },
    "cat_face": {
        "name": "Rosto de Gato",
        "category": "brinquedos",
        "difficulty": 2,
        "description": "Motivo de rosto de gato para brinquedos e decoração",
        "chart": [
            [0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
            [0, 0, 1, 1, 0, 0, 1, 1, 0, 0],
            [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
            [0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
            [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
            [1, 1, 0, 1, 1, 1, 1, 0, 1, 1],
            [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
            [0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
            [0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
            [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
        ],
        "repeat_w": 10,
        "repeat_h": 10,
        "tags": ["gato", "animal", "brinquedo", "rosto"],
    },
    "bear_face": {
        "name": "Rosto de Urso",
        "category": "brinquedos",
        "difficulty": 2,
        "description": "Motivo de rosto de urso para brinquedos e amigurumi",
        "chart": [
            [1, 1, 0, 0, 0, 0, 0, 0, 1, 1],
            [1, 1, 1, 0, 0, 0, 0, 1, 1, 1],
            [1, 1, 1, 1, 0, 0, 1, 1, 1, 1],
            [1, 0, 1, 0, 0, 0, 0, 1, 0, 1],
            [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
            [1, 1, 0, 1, 1, 1, 1, 0, 1, 1],
            [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
            [1, 1, 1, 0, 0, 0, 0, 1, 1, 1],
            [1, 1, 0, 0, 0, 0, 0, 0, 1, 1],
            [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        ],
        "repeat_w": 10,
        "repeat_h": 10,
        "tags": ["urso", "animal", "brinquedo", "rosto"],
    },
    "bunny": {
        "name": "Coelhinho",
        "category": "brinquedos",
        "difficulty": 2,
        "description": "Motivo de coelho para roupas e brinquedos infantis",
        "chart": [
            [0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
            [0, 1, 1, 0, 0, 0, 0, 1, 1, 0],
            [1, 1, 1, 1, 0, 0, 1, 1, 1, 1],
            [1, 1, 0, 1, 0, 0, 1, 0, 1, 1],
            [1, 1, 0, 0, 0, 0, 0, 0, 1, 1],
            [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
            [0, 1, 1, 0, 1, 1, 0, 1, 1, 0],
            [0, 0, 1, 0, 1, 1, 0, 1, 0, 0],
            [0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
        ],
        "repeat_w": 10,
        "repeat_h": 10,
        "tags": ["coelho", "animal", "infantil"],
    },
    "paw_print": {
        "name": "Patinha",
        "category": "brinquedos",
        "difficulty": 1,
        "description": "Pegada de animal para decoração infantil",
        "chart": [
            [0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
            [0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
            [0, 0, 1, 0, 1, 1, 0, 1, 0, 0],
            [0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
            [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
            [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
            [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
            [0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        ],
        "repeat_w": 10,
        "repeat_h": 10,
        "tags": ["pata", "animal", "infantil"],
    },
    "shell_stitch": {
        "name": "Ponto Concha",
        "category": "bebe",
        "difficulty": 2,
        "description": "Padrão de conchas para mantas e roupas de bebê",
        "chart": [
            [0, 0, 1, 0, 1, 0, 0],
            [0, 1, 0, 0, 0, 1, 0],
            [1, 0, 0, 0, 0, 0, 1],
            [0, 1, 0, 0, 0, 1, 0],
            [0, 0, 1, 0, 1, 0, 0],
        ],
        "repeat_w": 7,
        "repeat_h": 5,
        "tags": ["concha", "bebe", "manta"],
    },
    "baby_eyelet": {
        "name": "Casaquinho Olhinhos",
        "category": "bebe",
        "difficulty": 2,
        "description": "Padrão de furinhos para casacos e sapatinhos de bebê",
        "chart": [
            [0, 0, 0, 1, 0, 0, 0],
            [0, 0, 0, 1, 0, 0, 0],
            [0, 0, 0, 1, 0, 0, 0],
            [1, 1, 1, 1, 1, 1, 1],
            [0, 0, 0, 1, 0, 0, 0],
            [0, 0, 0, 1, 0, 0, 0],
            [0, 0, 0, 1, 0, 0, 0],
        ],
        "repeat_w": 7,
        "repeat_h": 7,
        "tags": ["bebe", "casaquinho", "furos"],
    },
    "baby_wave": {
        "name": "Ondinhas Bebê",
        "category": "bebe",
        "difficulty": 1,
        "description": "Ondas suaves para mantas e roupinhas de bebê",
        "chart": [
            [1, 1, 1, 0, 0, 0],
            [0, 1, 1, 1, 0, 0],
            [0, 0, 1, 1, 1, 0],
            [0, 0, 0, 1, 1, 1],
        ],
        "repeat_w": 6,
        "repeat_h": 4,
        "tags": ["bebe", "ondas", "manta"],
    },
    "duckling": {
        "name": "Patinho",
        "category": "animais",
        "difficulty": 2,
        "description": "Motivo de patinho para decoração e roupas infantis",
        "chart": [
            [0, 0, 1, 1, 0, 0, 0, 0],
            [0, 0, 1, 1, 1, 0, 0, 0],
            [0, 1, 1, 1, 1, 1, 0, 0],
            [1, 1, 1, 1, 1, 1, 1, 0],
            [1, 0, 0, 1, 1, 1, 1, 0],
            [1, 1, 1, 1, 1, 1, 1, 1],
            [0, 1, 0, 1, 0, 1, 0, 1],
            [0, 0, 0, 0, 0, 0, 0, 0],
        ],
        "repeat_w": 8,
        "repeat_h": 8,
        "tags": ["pato", "animal", "infantil"],
    },
    "bird_motif": {
        "name": "Passarinho",
        "category": "animais",
        "difficulty": 2,
        "description": "Peixinho simples para roupas e decoração",
        "chart": [
            [0, 0, 0, 1, 0, 0, 0, 0],
            [0, 1, 1, 1, 1, 0, 0, 0],
            [1, 1, 1, 1, 1, 1, 0, 0],
            [0, 1, 1, 1, 1, 1, 1, 0],
            [1, 1, 1, 1, 1, 1, 1, 0],
            [0, 1, 1, 1, 1, 0, 0, 0],
            [0, 0, 0, 1, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0],
        ],
        "repeat_w": 8,
        "repeat_h": 8,
        "tags": ["passaro", "animal", "decorativo"],
    },
    "fish_motif": {
        "name": "Peixinho",
        "category": "animais",
        "difficulty": 2,
        "description": "Peixinho simples para roupas e decoração",
        "chart": [
            [0, 0, 0, 0, 1, 0, 0, 0],
            [0, 0, 0, 1, 1, 0, 0, 0],
            [1, 1, 1, 1, 1, 1, 0, 0],
            [1, 1, 1, 1, 1, 1, 1, 0],
            [1, 1, 1, 1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1, 1, 1, 0],
            [1, 1, 1, 1, 1, 1, 0, 0],
            [0, 0, 0, 1, 1, 0, 0, 0],
        ],
        "repeat_w": 8,
        "repeat_h": 8,
        "tags": ["peixe", "animal", "decorativo"],
    },
    "star_motif": {
        "name": "Estrela",
        "category": "outros",
        "difficulty": 2,
        "description": "Motivo de estrela para decoração",
        "chart": [
            [0, 0, 0, 1, 0, 0, 0],
            [0, 0, 1, 1, 1, 0, 0],
            [0, 1, 0, 1, 0, 1, 0],
            [1, 1, 1, 1, 1, 1, 1],
            [0, 1, 0, 1, 0, 1, 0],
            [0, 0, 1, 1, 1, 0, 0],
            [0, 0, 0, 1, 0, 0, 0],
        ],
        "repeat_w": 7,
        "repeat_h": 7,
        "tags": ["estrela", "decorativo"],
    },
    "zigzag": {
        "name": "Ziguezague",
        "category": "outros",
        "difficulty": 1,
        "description": "Linhas diagonais em ziguezague para bordas e detalhes",
        "chart": [
            [1, 1, 0, 0, 0, 0],
            [0, 1, 1, 0, 0, 0],
            [0, 0, 1, 1, 0, 0],
            [0, 0, 0, 1, 1, 0],
        ],
        "repeat_w": 6,
        "repeat_h": 4,
        "tags": ["ziguezague", "geometrico"],
    },
    "chevron": {
        "name": "Chevron",
        "category": "outros",
        "difficulty": 2,
        "description": "Padrão Chevron clássico em V para mantas e cachecóis",
        "chart": [
            [0, 0, 1, 0, 0, 1, 0, 0],
            [0, 1, 0, 0, 0, 0, 1, 0],
            [1, 0, 0, 0, 0, 0, 0, 1],
            [0, 1, 0, 0, 0, 0, 1, 0],
            [0, 0, 1, 0, 0, 1, 0, 0],
        ],
        "repeat_w": 8,
        "repeat_h": 5,
        "tags": ["chevron", "geometrico", "manta"],
    },
    "cross_stitch": {
        "name": "Cruz",
        "category": "outros",
        "difficulty": 1,
        "description": "Padrão de cruzes para textura e detalhes",
        "chart": [
            [1, 0, 1],
            [0, 1, 0],
            [1, 0, 1],
        ],
        "repeat_w": 3,
        "repeat_h": 3,
        "tags": ["cruz", "textura"],
    },
}

PATTERN_KEYS = sorted(STITCH_LIBRARY.keys())

CATEGORIES = [
    ("basicos", "Básicos"),
    ("canelados", "Canelados"),
    ("basket_weave", "Basket Weave"),
    ("diagonais", "Diagonais"),
    ("diamantes", "Diamantes"),
    ("rendas", "Rendas"),
    ("deslizados", "Deslizados"),
    ("coracoes", "Corações"),
    ("meias", "Meias / Socks"),
    ("brinquedos", "Brinquedos / Toys"),
    ("bebe", "Bebê / Baby"),
    ("animais", "Animais"),
    ("outros", "Outros"),
]

CUSTOM_PATTERNS_FILE = "custom_patterns.json"

import json
import os

def load_custom_patterns():
    if os.path.exists(CUSTOM_PATTERNS_FILE):
        try:
            with open(CUSTOM_PATTERNS_FILE, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            return {}
    return {}

def save_custom_pattern(pid, data):
    patterns = load_custom_patterns()
    patterns[pid] = data
    with open(CUSTOM_PATTERNS_FILE, "w", encoding="utf-8") as f:
        json.dump(patterns, f, ensure_ascii=False, indent=2)

def delete_custom_pattern(pid):
    patterns = load_custom_patterns()
    if pid in patterns:
        del patterns[pid]
        with open(CUSTOM_PATTERNS_FILE, "w", encoding="utf-8") as f:
            json.dump(patterns, f, ensure_ascii=False, indent=2)
        return True
    return False

def get_all_patterns():
    combined = dict(STITCH_LIBRARY)
    custom = load_custom_patterns()
    for pid, pdata in custom.items():
        pdata["id"] = pid
        pdata["is_custom"] = True
        combined[pid] = pdata
    return combined
